# Generated by Django 5.0.3 on 2024-03-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_feedmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedModel',
            new_name='PostModel',
        ),
    ]
