# Generated by Django 5.0.3 on 2024-03-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_feedmodel_alter_postmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('stock', models.IntegerField(default=0)),
                ('availability', models.CharField(choices=[('In Stock', 'In stock'), ('Out of Stock', 'Out of Stock')], default='Out of Stock', max_length=20)),
            ],
        ),
    ]
