# Generated by Django 4.1.7 on 2024-03-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_alter_productmodel_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemModel',
        ),
    ]
