# Generated by Django 4.1.7 on 2024-03-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_delete_itemmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
