# Generated by Django 4.1.7 on 2024-03-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_delete_group_delete_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedModel',
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
